export enum PAGES {
  ROOT = '/',
  SIGN_IN = '/signin',
  SIGN_UP = '/signup',
  FEEDBACK = '/feedback',
  CATEGORY = '/category/:id',
  AUTOPARTS = '/autoparts',
  AUTOPART = '/autoparts/:id',
  PROFILE = '/profile',
  FAVORITES = '/profile/favorites',
  ADMIN_PANEL = '/profile/admin-panel',
  ORDERS = '/profile/orders',
  CART = '/profile/cart',
  PROFILE_EDIT = '/profile/edit',
  PROFILE_CONTACTS = '/profile/contacts',
}
